#!/usr/bin/env bash

# TODO: Add header: describe jess, credit iRedMail, add GNU License text.

# Exit when a command fails.
set -o errexit

# Exit status of last command is returned.
set -o pipefail

# Exit when undeclared variable is used.
set -o nounset

# Constants:
readonly LOGGER="log4sh"
readonly CONFIG_FILE="jess_config"

# TODO: Load variables

main()
{
  readonly ROOT_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  readonly DEPENDENCIES_DIRECTORY="${ROOT_DIRECTORY}/../dependencies"
  readonly LOGGER_DIRECTORY="${DEPENDENCIES_DIRECTORY}/${LOGGER}"
  readonly CONFIG_DIRECTORY="${ROOT_DIRECTORY}/config"
  readonly CORE_DIRECTORY="${ROOT_DIRECTORY}/core"

  set_up_logging "${LOGGER_DIRECTORY}"
  load_config "${CONFIG_DIRECTORY}"
}

set_up_logging()
{
  if [ -r "${1}/${LOGGER}" ]; then
    LOG4SH_CONFIGURATION='none' . "$1/${LOGGER}"
  else
    echo "ERROR: could not load (log4sh)" >&2
    exit 1
  fi

  logger_setLevel INFO
  logger_info "Hello, world!"
}

load_config()
{
  if [ -r "${1}/${CONFIG_FILE}" ]; then
    . "$1/${CONFIG_FILE}"
  else
    echo "ERROR: could not load config (jess)" >&2
    exit 1
  fi
}

main
